import Head from "next/head";
import Image from "next/image";

import Header from "@components/Header/Header";
import Container from "@components/Container/Container";

import products from "../products.json";

import styles from "@styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.css"
        />
      </Head>
      <Header />
      <main className={styles.main}>
        <Container>
          <h1>Hyper Bros Trading Cards</h1>
          <h2>Avaliable Cards</h2>
          <ul className={styles.productList}>
            {products.map((product) => (
              <li key={product.title}>
                <Image
                  width="864"
                  height="1264"
                  alt="Bowser Holo"
                  src={product.src}
                />
                <h3>{product.title}</h3>
                <p> ${product.price}</p>
                <p>
                  <button
                    className="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-price={product.price}
                    data-item-url="/"
                    data-item-description=""
                    data-item-image={product.src}
                    data-item-name={product.title}
                  >
                    {" "}
                    Add to cart
                  </button>
                </p>
              </li>
            ))}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; Hyper Bros Trading Cards {new Date().getFullYear()}
      </footer>
      <script
        async
        src="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.js"
      ></script>
      <div
        hidden
        id="snipcart"
        data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}
      ></div>
    </div>
  );
}
